TELEGRAM_API_ID: api_id
TELEGRAM_API_HASH: api_hash
TELEGRAM_PHONE: +1234567890
TELEGRAM_DB_KEY: your_db_key
TWITTER_AUTHTOKEN: authtoken
TWITTER_CSRFTOKEN: csrftoken
DB_PATH: teledeck.db
MEDIA_PATH: /mnt/c/teledeck/static/media
TAGGER_URL: localhost:50051
ENV: development
PORT: 4000
SESSION_COOKIE_NAME: session
STATIC_DIR: "./assets"
MEDIA_DIR: "/mnt/c/teledeck/static"
RECYCLE_DIR: "/mnt/c/teledeck/recyclebin"
TAGGER_URL: localhost
TAGGER_PORT: 8081