// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: AI/proto/ai_server.proto

package ai_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageUrl string `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *ImageUrlRequest) Reset() {
	*x = ImageUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AI_proto_ai_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUrlRequest) ProtoMessage() {}

func (x *ImageUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AI_proto_ai_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUrlRequest.ProtoReflect.Descriptor instead.
func (*ImageUrlRequest) Descriptor() ([]byte, []int) {
	return file_AI_proto_ai_server_proto_rawDescGZIP(), []int{0}
}

func (x *ImageUrlRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type TagImageUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageUrl string  `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Cutoff   float32 `protobuf:"fixed32,2,opt,name=cutoff,proto3" json:"cutoff,omitempty"`
}

func (x *TagImageUrlRequest) Reset() {
	*x = TagImageUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AI_proto_ai_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagImageUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagImageUrlRequest) ProtoMessage() {}

func (x *TagImageUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AI_proto_ai_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagImageUrlRequest.ProtoReflect.Descriptor instead.
func (*TagImageUrlRequest) Descriptor() ([]byte, []int) {
	return file_AI_proto_ai_server_proto_rawDescGZIP(), []int{1}
}

func (x *TagImageUrlRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *TagImageUrlRequest) GetCutoff() float32 {
	if x != nil {
		return x.Cutoff
	}
	return 0
}

type ScoreResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score float32 `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *ScoreResult) Reset() {
	*x = ScoreResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AI_proto_ai_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResult) ProtoMessage() {}

func (x *ScoreResult) ProtoReflect() protoreflect.Message {
	mi := &file_AI_proto_ai_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResult.ProtoReflect.Descriptor instead.
func (*ScoreResult) Descriptor() ([]byte, []int) {
	return file_AI_proto_ai_server_proto_rawDescGZIP(), []int{2}
}

func (x *ScoreResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type TagResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags []*Tag `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *TagResult) Reset() {
	*x = TagResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AI_proto_ai_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagResult) ProtoMessage() {}

func (x *TagResult) ProtoReflect() protoreflect.Message {
	mi := &file_AI_proto_ai_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagResult.ProtoReflect.Descriptor instead.
func (*TagResult) Descriptor() ([]byte, []int) {
	return file_AI_proto_ai_server_proto_rawDescGZIP(), []int{3}
}

func (x *TagResult) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weight float32 `protobuf:"fixed32,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Tag    string  `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AI_proto_ai_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_AI_proto_ai_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_AI_proto_ai_server_proto_rawDescGZIP(), []int{4}
}

func (x *Tag) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Tag) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

var File_AI_proto_ai_server_proto protoreflect.FileDescriptor

var file_AI_proto_ai_server_proto_rawDesc = []byte{
	0x0a, 0x18, 0x41, 0x49, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x69, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x72, 0x22, 0x2e, 0x0a, 0x0f, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x49, 0x0a, 0x12, 0x54, 0x61, 0x67, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x75, 0x74, 0x6f, 0x66, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x63, 0x75, 0x74,
	0x6f, 0x66, 0x66, 0x22, 0x23, 0x0a, 0x0b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x32, 0x0a, 0x09, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x72, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x2f, 0x0a, 0x03,
	0x54, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x32, 0x9e, 0x01,
	0x0a, 0x0b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x72, 0x12, 0x48, 0x0a,
	0x0a, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x2e, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x72, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x72, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x06, 0x54, 0x61, 0x67, 0x55, 0x72,
	0x6c, 0x12, 0x20, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x72,
	0x2e, 0x54, 0x61, 0x67, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x72, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x0c,
	0x5a, 0x0a, 0x61, 0x69, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AI_proto_ai_server_proto_rawDescOnce sync.Once
	file_AI_proto_ai_server_proto_rawDescData = file_AI_proto_ai_server_proto_rawDesc
)

func file_AI_proto_ai_server_proto_rawDescGZIP() []byte {
	file_AI_proto_ai_server_proto_rawDescOnce.Do(func() {
		file_AI_proto_ai_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_AI_proto_ai_server_proto_rawDescData)
	})
	return file_AI_proto_ai_server_proto_rawDescData
}

var file_AI_proto_ai_server_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_AI_proto_ai_server_proto_goTypes = []any{
	(*ImageUrlRequest)(nil),    // 0: image_scorer.ImageUrlRequest
	(*TagImageUrlRequest)(nil), // 1: image_scorer.TagImageUrlRequest
	(*ScoreResult)(nil),        // 2: image_scorer.ScoreResult
	(*TagResult)(nil),          // 3: image_scorer.TagResult
	(*Tag)(nil),                // 4: image_scorer.Tag
}
var file_AI_proto_ai_server_proto_depIdxs = []int32{
	4, // 0: image_scorer.TagResult.tags:type_name -> image_scorer.Tag
	0, // 1: image_scorer.ImageScorer.PredictUrl:input_type -> image_scorer.ImageUrlRequest
	1, // 2: image_scorer.ImageScorer.TagUrl:input_type -> image_scorer.TagImageUrlRequest
	2, // 3: image_scorer.ImageScorer.PredictUrl:output_type -> image_scorer.ScoreResult
	3, // 4: image_scorer.ImageScorer.TagUrl:output_type -> image_scorer.TagResult
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_AI_proto_ai_server_proto_init() }
func file_AI_proto_ai_server_proto_init() {
	if File_AI_proto_ai_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AI_proto_ai_server_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ImageUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AI_proto_ai_server_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TagImageUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AI_proto_ai_server_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ScoreResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AI_proto_ai_server_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TagResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AI_proto_ai_server_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AI_proto_ai_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AI_proto_ai_server_proto_goTypes,
		DependencyIndexes: file_AI_proto_ai_server_proto_depIdxs,
		MessageInfos:      file_AI_proto_ai_server_proto_msgTypes,
	}.Build()
	File_AI_proto_ai_server_proto = out.File
	file_AI_proto_ai_server_proto_rawDesc = nil
	file_AI_proto_ai_server_proto_goTypes = nil
	file_AI_proto_ai_server_proto_depIdxs = nil
}
