apiVersion: v1
kind: Service
metadata:
  name: teledeck-ai
spec:
  type: LoadBalancer
  selector:
    app: teledeck-ai
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 9090
      targetPort: 9090
