"""thumbnail

Revision ID: 004318c1c5a6
Revises: 512ef2b007dc
Create Date: 2024-12-18 00:57:30.569441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004318c1c5a6'
down_revision: Union[str, None] = '512ef2b007dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thumbnails",
        sa.Column("media_item_id", sa.VARCHAR, nullable=False),
        sa.Column("filename", sa.VARCHAR, nullable=False),
        sa.ForeignKeyConstraint(
            ["media_item_id"],
            ["media_items.id"],
        ),
        sa.PrimaryKeyConstraint("media_item_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thumbnails')
    # ### end Alembic commands ###
