// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ai_server

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockUnsafeImageScorerServer creates a new instance of MockUnsafeImageScorerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeImageScorerServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeImageScorerServer {
	mock := &MockUnsafeImageScorerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnsafeImageScorerServer is an autogenerated mock type for the UnsafeImageScorerServer type
type MockUnsafeImageScorerServer struct {
	mock.Mock
}

type MockUnsafeImageScorerServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeImageScorerServer) EXPECT() *MockUnsafeImageScorerServer_Expecter {
	return &MockUnsafeImageScorerServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedImageScorerServer provides a mock function for the type MockUnsafeImageScorerServer
func (_mock *MockUnsafeImageScorerServer) mustEmbedUnimplementedImageScorerServer() {
	_mock.Called()
	return
}

// MockUnsafeImageScorerServer_mustEmbedUnimplementedImageScorerServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedImageScorerServer'
type MockUnsafeImageScorerServer_mustEmbedUnimplementedImageScorerServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedImageScorerServer is a helper method to define mock.On call
func (_e *MockUnsafeImageScorerServer_Expecter) mustEmbedUnimplementedImageScorerServer() *MockUnsafeImageScorerServer_mustEmbedUnimplementedImageScorerServer_Call {
	return &MockUnsafeImageScorerServer_mustEmbedUnimplementedImageScorerServer_Call{Call: _e.mock.On("mustEmbedUnimplementedImageScorerServer")}
}

func (_c *MockUnsafeImageScorerServer_mustEmbedUnimplementedImageScorerServer_Call) Run(run func()) *MockUnsafeImageScorerServer_mustEmbedUnimplementedImageScorerServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeImageScorerServer_mustEmbedUnimplementedImageScorerServer_Call) Return() *MockUnsafeImageScorerServer_mustEmbedUnimplementedImageScorerServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeImageScorerServer_mustEmbedUnimplementedImageScorerServer_Call) RunAndReturn(run func()) *MockUnsafeImageScorerServer_mustEmbedUnimplementedImageScorerServer_Call {
	_c.Run(run)
	return _c
}
