# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ai_server_pb2 as ai__server__pb2


class ImageScorerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictUrl = channel.unary_unary(
                '/image_scorer.ImageScorer/PredictUrl',
                request_serializer=ai__server__pb2.ImageUrlRequest.SerializeToString,
                response_deserializer=ai__server__pb2.ScoreResult.FromString,
                )


class ImageScorerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageScorerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictUrl,
                    request_deserializer=ai__server__pb2.ImageUrlRequest.FromString,
                    response_serializer=ai__server__pb2.ScoreResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'image_scorer.ImageScorer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageScorer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/image_scorer.ImageScorer/PredictUrl',
            ai__server__pb2.ImageUrlRequest.SerializeToString,
            ai__server__pb2.ScoreResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
